Misc bugfixes
WISDEM/ORBIT pull request #104
Opened 2021-06-04 17:46 UTC by JakeNunemaker

- Add project_capex back into total_capex summation
- Modified default number of substations calculation
- Revised loop ParametricManager.from_config()
- Closes #92

2021-06-04 17:59 UTC, JakeNunemaker commented
@Matt-Shields We've talked about the first 2 already. The 3rd bullet point was just a small bug but I'd like to run the 4th one by you before I merge it in:

I modified some of the vessel logic so that a vessel can always carry 1 set of components (monopile + transition piece, turbine set) even if the mass or deck space would exceed the vessel capacity. It still works the same way past the first set though, so if a vessel can fit more than 1 it will calculate based on the deck space / cargo capacity. I know this has given Garrett + WISDEM trouble in the past and this was giving me trouble in the parametric ORBIT runs. I think this is a good compromise but I'd be interested if you think having the hard stop in there adds value. If so, I could add a flag to toggle this feature on/off.

2021-06-10 15:18 UTC, Matt-Shields requested changes
I'm fine with avoiding the hard stop on the vessel capacities, but can we print a Warning if any of the cargo sets exceed the vessel capabilities?

2021-06-10 21:46 UTC, JakeNunemaker commented
@Matt-Shields I added a warning and some logic in ProjectManager so it doesn't print out every time it does this check.

2021-06-10 21:56 UTC, Matt-Shields approved these changes

2021-06-11 21:11 UTC, merged