Electrical refactor
WISDEM/ORBIT pull request #112
Opened 2021-12-20 17:53 UTC by sbredenk

2021-12-20 19:53 UTC, JakeNunemaker commented
@Matt-Shields This is a draft PR that Sophie and I are working on.

@both Looking at the failing tests, it looks like several of them are from a new required property ("cable_type") in the Cable class. Do we want to require a type to be defined in the cable, or would it be okay to assume cables are HVAC unless specified?

2021-12-20 19:57 UTC, JakeNunemaker commented
@sbredenk We should add documentation regarding the difference between using the old two modules vs your new module (if we are going to keep both). We'll want to make it obvious that you shouldn't use all three as there would be costs would be double counted.

2021-12-20 19:58 UTC, JakeNunemaker commented on ORBIT/phases/design/_cables.py
> +#        else:
Remove commented code if not required.

2021-12-20 19:59 UTC, JakeNunemaker commented on tests/phases/design/test_electrical_design.py
> +
Remove extra lines. I should get you set up with pre-commit hooks sometime. They help a lot with automating random formatting things like this.

2021-12-20 20:27 UTC, JakeNunemaker commented
@sbredenk I've fixed all of the irrelevant tests. I've included the default "cable_type" for now, but we should discuss with Matt if we want to include that or enforce a defined cable type.

The remaining tests look like they are specific to the electrical modules. It looks like you changed some of the electrical parameters in the cables as well as some of the back end methods in the _cables.py file. Can you go through the process of confirming that the numbers tested against are still correct given the changed calculations / parameters.

2022-06-20 19:06 UTC, JakeNunemaker requested changes
@sbredenk This looks really good and I think it's pretty close to ready. The new requirement for cable type is causing some other tests to fail. Adding a default cable type and fixing the related config definitions / methods should fix those. There are also some other cable tests that are failing that seem to be related to changes in the `Cable` class. Can you also look into those tests to see if your changes impacted the old modules or if the tests need to be updated to reflect your changed?

2022-11-22 18:17 UTC, sbredenk commented on ORBIT/phases/design/electrical_export.py
> +            )
num_cables will never be odd for bipole because the number is calculated by 2*(ciel(plant_cap/cable_power))

2022-11-22 18:18 UTC, sbredenk commented on ORBIT/phases/install/cable_install/export.py
> +        self.cable_type = system["cable"]["cable_type"]
should I do both this and the 
..."cable_type": "str (optional, default: 'HVAC')" ... 
or just one?

2023-04-21 15:30 UTC, JakeNunemaker approved these changes

2023-04-21 15:30 UTC, merged